/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#27354c',
        'outline-variant': '#3c4947',
        'on-error-container': '#ffdad6',
        primary: '#4fdbc8',
        'on-surface-variant': '#bbcac6',
        outline: '#859490',
        'inverse-primary': '#006b5f',
        'tertiary-fixed-dim': '#9fcaff',
        secondary: '#4cd7f6',
        background: '#041329',
        'on-surface': '#d6e3ff',
        'surface-container': '#112036',
        'secondary-container': '#03b5d3',
        'on-secondary-fixed': '#001f26',
        'inverse-on-surface': '#233148',
        'on-background': '#d6e3ff',
        'on-primary-container': '#00423b',
        'error-container': '#93000a',
        'inverse-surface': '#d6e3ff',
        'on-tertiary-container': '#003c68',
        'on-tertiary': '#003258',
        'primary-fixed-dim': '#4fdbc8',
        'on-primary': '#003731',
        'on-primary-fixed': '#00201c',
        tertiary: '#9fcaff',
        'secondary-fixed': '#acedff',
        'tertiary-fixed': '#d1e4ff',
        'surface-dim': '#041329',
        'on-error': '#690005',
        'surface-container-low': '#0d1c32',
        'secondary-fixed-dim': '#4cd7f6',
        surface: '#041329',
        'on-tertiary-fixed-variant': '#00497d',
        'on-secondary-container': '#00424e',
        'surface-container-highest': '#27354c',
        'primary-container': '#14b8a6',
        'surface-tint': '#4fdbc8',
        'surface-container-high': '#1c2a41',
        'primary-fixed': '#71f8e4',
        'on-secondary': '#003640',
        'on-secondary-fixed-variant': '#004e5c',
        'surface-bright': '#2c3951',
        'tertiary-container': '#55a8fc',
        'on-primary-fixed-variant': '#005048',
        'surface-container-lowest': '#010e24',
        error: '#ffb4ab',
        'on-tertiary-fixed': '#001d36',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      animation: {
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'bar-fill': 'barFill 1.5s ease-out forwards',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        barFill: {
          from: { width: '0%' },
          to: { width: 'var(--bar-width)' },
        },
      },
    },
  },
  plugins: [],
};
